name: Deploy ECS Infrastructure

on:
  repository_dispatch:
    types: [deploy]

jobs:
  terraform-deploy:
    name: Terraform Init & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var="image_url=${{ secrets.IMAGE_URL }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="image_url=${{ secrets.IMAGE_URL }}"
